pipeline {
    agent any
    stages {
        stage('Create File') {
            steps {
                script {
                    sh 'echo "Hello, Jenkins!" >> test.txt'
                }
            }
        }

        stage('Archive Artifact') {
            steps {
                archiveArtifacts artifacts: 'test.txt', fingerprint: true
            }
        }
    }
}
